package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/weeb-vip/scraper-api/graph/generated"
	"github.com/weeb-vip/scraper-api/graph/model"
)

// FindAPIInfoByName is the resolver for the findApiInfoByName field.
func (r *entityResolver) FindAPIInfoByName(ctx context.Context, name string) (*model.APIInfo, error) {
	panic(fmt.Errorf("not implemented: FindAPIInfoByName - findApiInfoByName"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
