// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIInfo struct {
	// API Info of the ScraperAPI
	ScraperAPI *ScraperAPI `json:"scraperAPI"`
	// Name of the API
	Name string `json:"name"`
}

func (APIInfo) IsEntity() {}

type Link struct {
	// ID of the link
	ID string `json:"id"`
	// name of anime
	Name string `json:"name"`
	// animeid Link
	AnimeID string `json:"animeID"`
	// TheTVDB ID
	ThetvdbID string `json:"thetvdbID"`
	// season
	Season int `json:"season"`
}

type SaveLinkInput struct {
	// Animeid Link to save
	AnimeID string `json:"animeID"`
	// TheTVDB ID
	ThetvdbID string `json:"thetvdbID"`
	// season
	Season int `json:"season"`
	// Name of anime
	Name string `json:"name"`
}

type ScraperAPI struct {
	// Version of event scraper-api service
	Version string `json:"version"`
}

type TheTVDBAnime struct {
	// ID of the anime
	ID string `json:"id"`
	// Anime title
	Title string `json:"title"`
	// Anime Link
	Link string `json:"link"`
	// Anime Poster
	Image *string `json:"image,omitempty"`
	// Anime Release Year
	Year *string `json:"year,omitempty"`
	// Translations
	Translations []*TranslationTuple `json:"translations,omitempty"`
	// studios
	Studios []string `json:"studios,omitempty"`
	// Genres
	Genres []string `json:"genres,omitempty"`
}

type TheTVDBEpisode struct {
	// ID of the episode
	ID string `json:"id"`
	// Episode Title
	Title string `json:"title"`
	// Episode Number
	EpisodeNumber int `json:"episodeNumber"`
	// Season Number
	SeasonNumber int `json:"seasonNumber"`
	// Episode Link
	Link string `json:"link"`
	// Episode Image
	Image *string `json:"image,omitempty"`
	// Episode Description
	Description *string `json:"description,omitempty"`
	// Episode Air Date
	AirDate *string `json:"airDate,omitempty"`
}

type TheTVDBSearchInput struct {
	// Search query
	Query string `json:"query"`
}

type TranslationTuple struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}
