global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'metrics'
    static_configs:
      - targets: [ '172.16.150.106:2112' ]
    metrics_path: /metrics
  - job_name: 'metrics-node'
    static_configs:
      - targets: [ '172.16.150.106:2113' ]
    metrics_path: /metrics